[package]
name = "dinoscript"
version = "0.1.0"
edition = "2021"

[dependencies]
dinoscript_core = { path = "../dinoscript_core" }
dinoscript_std = { path = "../dinoscript_std" }

[dev-dependencies]
glob = "0.3.1"
itertools = "0.13.0"
