[package]
name = "dinoscript_core"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = {version="1.0.0", features=["debug"]}
indexmap = "2.6.0"
itertools = "0.13.0"
pest = "2.7.11"
pest_derive = "2.7.11"


[lib]
name = "dinoscript_core"
